version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/cloudcode
    binary: cloudcode
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - formats: [binary]
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

release:
  extra_files:
    - glob: ./install.sh
      name_template: install.sh

checksum:
  name_template: checksums.txt
